server.forward-headers-strategy=native
server.tomcat.redirect-context-root=false
server.tomcat.remoteip.internal-proxies=${OCV_TRUSTED_PROXY_CIDRS}
server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
server.tomcat.remoteip.host-header=X-Forwarded-Host
server.tomcat.remoteip.port-header=X-Forwarded-Port