package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an immutable accounting submission attempt.
 *
 * @param value UUID generated by the application
 */
public record AccountingSubmissionAttemptId(
        UUID value) {

    public AccountingSubmissionAttemptId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "accounting submission attempt id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}