package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of a close state transition.
 *
 * @param value UUID value generated by the application
 */
public record CloseStateTransitionId(UUID value) {

    public CloseStateTransitionId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "close state transition id must not be null");
        }
    }

}
