package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an Operational Close consolidation.
 *
 * @param value UUID value generated by the application
 */
public record ConsolidationId(UUID value) {

    public ConsolidationId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "consolidation id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}