package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an Event Authorization.
 *
 * @param value UUID generated by the application
 */
public record EventAuthorizationId(UUID value) {

    public EventAuthorizationId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "event authorization id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}