package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an Operational Close.
 *
 * @param value UUID value generated by the application
 */
public record OperationalCloseId(UUID value) {

    public OperationalCloseId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "operational close id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}
