package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an accounting submission rejection issue.
 *
 * @param value UUID generated by the application
 */
public record SubmissionAttemptIssueId(
        UUID value) {

    public SubmissionAttemptIssueId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "submission attempt issue id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}