package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of Supporting Evidence.
 *
 * @param value UUID generated by the application
 */
public record SupportingEvidenceId(UUID value) {

    public SupportingEvidenceId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "supporting evidence id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}