package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an immutable Validation Result.
 *
 * @param value UUID generated by the application
 */
public record ValidationResultId(
        UUID value) {

    public ValidationResultId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "validation result id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}