package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of a Validation Alert.
 *
 * @param value UUID generated by the application
 */
public record ValidationAlertId(
        UUID value) {

    public ValidationAlertId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "validation alert id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}