package com.marceloituccayasi.ocv.operationalclose.domain;

import java.util.UUID;

/**
 * Identifier of an append-only Validation Alert transition.
 *
 * @param value UUID generated by the application
 */
public record ValidationAlertTransitionId(
        UUID value) {

    public ValidationAlertTransitionId {
        if (value == null) {
            throw new IllegalArgumentException(
                    "validation alert transition id must not be null");
        }
    }

    @Override
    public String toString() {
        return value.toString();
    }

}